// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-AzsmG0U6t1aUGttZq_hHitsNuw-uDOQ',
    appId: '1:796909241665:android:ee310721f2ab5e24b74dc0',
    messagingSenderId: '796909241665',
    projectId: 'fir-c1ae3',
    storageBucket: 'fir-c1ae3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfd6KpYAox-1GdT0-cbvUCZQ7eoVYtXNA',
    appId: '1:796909241665:ios:030f1df46441ce9fb74dc0',
    messagingSenderId: '796909241665',
    projectId: 'fir-c1ae3',
    storageBucket: 'fir-c1ae3.appspot.com',
    androidClientId: '796909241665-kcitmi4ruhb6d7lvc0dn64l3jffuvhuc.apps.googleusercontent.com',
    iosClientId: '796909241665-qm9lphea0qrjt2j1uj9fbaakiaemicea.apps.googleusercontent.com',
    iosBundleId: 'com.example.demoSeminar',
  );
}
